#!/usr/bin/env bash

[ -z "$SDL3_DIR" ] && echo "WARNING: SDL3_DIR is not defined"
[ ! -d "$SDL3_DIR" ] && echo "WARNING: SDL3_DIR is defined, but $SDL3_DIR is not a directory"

# for clangd under MSYS, match first /{DRIVE LETTER}/ and replace with {DRIVE LETTER}:/
_SDL3_DIR=$(echo "$SDL3_DIR" | sed 's|^/\([a-z]*\)/|\1\:/|') 
[ ! -d "$_SDL3_DIR" ] && _SDL3_DIR="$SDL3_DIR"

{
echo "\
CompileFlags: 
  Add: 
    - -std=c++20 
    - -I$PWD/src/ 
    - -I$PWD/lib/shfl/
    - -I$PWD/lib/raylib-5.5_linux_amd64/include
    - -I$PWD/lib/raylib-5.5_macos/include
    - -I$PWD/lib/raylib-5.5_win64_mingw-w64/include
    - -I$_SDL3_DIR/include/"
} > .clangd
